version: '3.8'

services:
  backend:
    build: ./backend
    container_name: anesthesia-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data

  frontend:
    build: ./frontend
    container_name: anesthesia-frontend
    restart: unless-stopped
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - API_URL=http://localhost:8000/api
